# Generated by Django 3.2.15 on 2022-08-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0058_alter_ariza_gelentelefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenTelefon',
            field=models.CharField(max_length=12),
        ),
    ]
