# Generated by Django 3.2.15 on 2022-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0059_alter_ariza_gelentelefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariza',
            name='gelenAciklama',
            field=models.TextField(max_length=2000),
        ),
    ]
