# Generated by Django 3.2.15 on 2022-10-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0062_remove_kesif_kesifyapilanyertarihi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kesif',
        ),
    ]
