# Generated by Django 3.2.15 on 2022-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_kesif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='kesifSenaryosu',
            field=models.CharField(max_length=2000),
        ),
    ]
