# Generated by Django 3.2.15 on 2022-10-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_alter_kesif_kesifsenaryosu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KesifMalzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesifKameraSayisi', models.IntegerField(default=0)),
                ('kesifDirekSayisi', models.IntegerField(default=0)),
                ('kesifSwitchSayisi', models.IntegerField(default=0)),
                ('kesifBigisayarConfigi', models.CharField(default='yok', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
