# Generated by Django 3.2.15 on 2022-10-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0066_kesifmalzeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesif',
            name='KesifMalzemeler',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.kesifmalzeme'),
        ),
    ]
