# Generated by Django 3.2.15 on 2022-10-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_kesif_kesifmalzemeler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesif',
            name='kesifCctvVarMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kesif',
            name='kesifOlayVarMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kesif',
            name='kesifPTSVarMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kesif',
            name='KesifMalzemeler',
            field=models.ForeignKey(blank=True, default=35, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.kesifmalzeme'),
        ),
    ]
