# Generated by Django 3.2.15 on 2022-10-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0069_auto_20221017_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='KesifOlayMalzemeler',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.kesifolaymalzeme'),
        ),
        migrations.AlterField(
            model_name='kesif',
            name='KesifPTSMalzemeler',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.kesifptsmalzeme'),
        ),
    ]
