# Generated by Django 3.2.15 on 2022-10-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_kesifptsmalzeme_kesifptsyeradi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kesif',
            old_name='KesifOlayMalzemeler',
            new_name='KesifOlayMalzemelerid',
        ),
        migrations.RenameField(
            model_name='kesif',
            old_name='KesifPTSMalzemeler',
            new_name='KesifPTSMalzemelerid',
        ),
    ]
