# Generated by Django 3.2.15 on 2022-10-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_auto_20221017_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifDirekUzunlugu',
            field=models.IntegerField(default=2),
        ),
    ]
