# Generated by Django 3.2.15 on 2022-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0076_auto_20221019_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifDirekUzunlugu',
            field=models.CharField(default='yok', max_length=25),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPatchPanelTipi',
            field=models.CharField(default='yok', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifSwitchTipi',
            field=models.CharField(default='yok', max_length=25, null=True),
        ),
    ]
