# Generated by Django 3.2.15 on 2022-10-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0077_auto_20221020_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPanoTipi',
            field=models.CharField(default='yok', max_length=50),
        ),
    ]
