# Generated by Django 3.2.15 on 2022-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0080_auto_20221026_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifExtraKameraTipi',
            field=models.CharField(choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], default='yok', max_length=25),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifKameraTipi',
            field=models.CharField(choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], default='yok', max_length=25),
        ),
    ]
