# Generated by Django 3.2.15 on 2022-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0082_auto_20221026_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSDirekAçıklama',
            field=models.TextField(default='yok', max_length=200),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFlanshSayisi',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=25),
        ),
    ]
