# Generated by Django 3.2.15 on 2022-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0083_auto_20221027_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kesifptsmalzeme',
            old_name='kesifPTSBigisayarConfigi',
            new_name='kesifPTSBilgisayarConfigi',
        ),
        migrations.RenameField(
            model_name='kesifptsmalzeme',
            old_name='kesifPTSIoKartSayisi',
            new_name='kesifPTSBilgisayarSayısı',
        ),
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartmodulaciklamasi',
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartModulSayısı',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartSayısı',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartTipi',
            field=models.CharField(choices=[('TİNY', 'TİNY'), ('AKSİYON', 'AKSİYON')], default='yok', max_length=25),
        ),
    ]
