# Generated by Django 3.2.15 on 2022-10-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0084_auto_20221027_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSwitchTipi',
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSwitchPortSayisi',
            field=models.CharField(choices=[('5', '5'), ('8', '8')], default='yok', max_length=25, null=True),
        ),
    ]
