# Generated by Django 3.2.15 on 2022-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0085_auto_20221027_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSKameraBoatSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
