# Generated by Django 3.2.15 on 2022-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0086_kesifptsmalzeme_kesifptskameraboatsayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSKameraAdaptorSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
