# Generated by Django 3.2.15 on 2022-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0087_kesifptsmalzeme_kesifptskameraadaptorsayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSExtraKameraAdaptorSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
