# Generated by Django 3.2.15 on 2022-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0088_kesifptsmalzeme_kesifptsextrakameraadaptorsayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartAdaptorSayısı',
            field=models.IntegerField(default=0),
        ),
    ]
