# Generated by Django 3.2.15 on 2022-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0090_auto_20221027_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPanoOlcusu',
            field=models.CharField(default='yok', max_length=50),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPanoTipi',
            field=models.CharField(choices=[('3x1.5 TTR', '3x1.5 TTR'), ('3x2.5 TTR', '3x2.5 TTR'), ('2x1.5 TTR', '2x1.5 TTR')], default='yok', max_length=50),
        ),
    ]
