# Generated by Django 3.2.15 on 2022-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0093_alter_image_kesifimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerModeli',
            field=models.CharField(default='yok', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSLedEkranModeli',
            field=models.CharField(default='yok', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSLedEkranSayisi',
            field=models.IntegerField(default=0),
        ),
    ]
