# Generated by Django 3.2.15 on 2022-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0094_auto_20221102_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerKolBoyu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSwitchPoeMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerModeli',
            field=models.CharField(choices=[('3250', '3250'), ('G-4000', 'G-4000'), ('4040E', '4040E'), ('2080E', '2080E'), ('GT-4', 'GT-4'), ('GT-8', 'GT-8')], default='yok', max_length=25),
        ),
    ]
