# Generated by Django 3.2.15 on 2022-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0095_auto_20221102_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSCibikModuleVarMi',
        ),
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberVarMi',
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberAdaptorSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberAdaptorTipi',
            field=models.CharField(choices=[('SC-LC', 'SC-LC'), ('SC-SC', 'SC-SC'), ('LC-LC', 'LC-LC')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberKabloModeli',
            field=models.CharField(choices=[('2 Core', '2 Core'), ('4 Core', '4 Core'), ('8 Core', '8 Core'), ('16 Core', '16 Core')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchCordSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchCordTipi',
            field=models.CharField(choices=[('SC-LC', 'SC-LC'), ('SC-SC', 'SC-SC'), ('LC-LC', 'LC-LC')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchPanelEkKasetSayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchPanelTipi',
            field=models.CharField(choices=[('2 li', '2 li'), ('4 lu', '4 lu'), ('8 li', '8 li'), ('12 li', '12 li')], default='yok', max_length=25),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSwitchPortSayisi',
            field=models.CharField(choices=[('5', '5'), ('8', '8'), ('5+2', '5+2'), ('8+2', '8+2'), ('16+2', '16+2'), ('8+4', '8+4'), ('16+4', '16+4')], default='yok', max_length=25, null=True),
        ),
    ]
