# Generated by Django 3.2.15 on 2022-11-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0096_auto_20221102_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageKesif',
        ),
    ]
