# Generated by Django 3.2.15 on 2022-11-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0097_rename_image_imagekesif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSyeradi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
