# Generated by Django 3.2.15 on 2022-11-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0099_alter_kesifptsmalzeme_kesifptskamerasayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSKameraSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
