# Generated by Django 3.2.15 on 2022-11-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0101_auto_20221108_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerKolBoyu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBariyerSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBilgisayarConfigi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSBilgisayarSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSCAT6kablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSCibikModuleSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSDT8kablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSDirekAçıklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSDirekSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSDirekUzunlugu',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSEnerjikablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSExtraKameraSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSExtraKameraTipi',
            field=models.CharField(blank=True, choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSFiberMetre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartAdaptorSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartModulSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSIoKartSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSLedEkranModeli',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSLedEkranSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPanoOlcusu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPanoSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchCordSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchPanelEkKasetSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSPatchPanelSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSpiralMetre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSpiralÇapı',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='kesifPTSSwitchSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
