# Generated by Django 3.2.15 on 2022-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0102_auto_20221108_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='kesifSenaryosu',
            field=models.TextField(),
        ),
    ]
