# Generated by Django 3.2.15 on 2022-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0103_alter_kesif_kesifsenaryosu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSMantarBariyerModeli',
            field=models.CharField(choices=[('3250', '3250'), ('G-4000', 'G-4000'), ('4040E', '4040E'), ('2080E', '2080E'), ('GT-4', 'GT-4'), ('GT-8', 'GT-8')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSMantarBariyerSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
