# Generated by Django 3.2.15 on 2022-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0105_auto_20221108_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSMantarBariyerModeli',
        ),
        migrations.RemoveField(
            model_name='kesifptsmalzeme',
            name='kesifPTSMantarBariyerSayisi',
        ),
        migrations.AddField(
            model_name='kesifptsmalzeme',
            name='kesifPTSMantarBariyerAciklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
