# Generated by Django 3.2.15 on 2022-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0106_auto_20221108_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBigisayarConfigi',
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBariyerKolBoyu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBariyerModeli',
            field=models.CharField(choices=[('3250', '3250'), ('G-4000', 'G-4000'), ('4040E', '4040E'), ('2080E', '2080E'), ('GT-4', 'GT-4'), ('GT-8', 'GT-8')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBariyerSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBilgisayarConfigi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayBilgisayarSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayCAT6kablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayCibikModuleSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayDT8kablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayDirekAçıklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayDirekUzunlugu',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayEnerjikabloTipi',
            field=models.CharField(choices=[('3x1.5 TTR', '3x1.5 TTR'), ('3x2.5 TTR', '3x2.5 TTR'), ('2x1.5 TTR', '2x1.5 TTR')], default='yok', max_length=50),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayEnerjikablometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayExtraKameraAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayExtraKameraSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayExtraKameraTipi',
            field=models.CharField(blank=True, choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayFiberAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayFiberAdaptorTipi',
            field=models.CharField(choices=[('SC-LC', 'SC-LC'), ('SC-SC', 'SC-SC'), ('LC-LC', 'LC-LC')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayFiberKabloModeli',
            field=models.CharField(choices=[('2 Core', '2 Core'), ('4 Core', '4 Core'), ('8 Core', '8 Core'), ('16 Core', '16 Core')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayFiberMetre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayFlanshSayisi',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayIoKartAdaptorSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayIoKartModulSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayIoKartSayısı',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayIoKartTipi',
            field=models.CharField(choices=[('TİNY', 'TİNY'), ('AKSİYON', 'AKSİYON')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayKameraAdaptorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayKameraBoatSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayKameraTipi',
            field=models.CharField(blank=True, choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLedEkranModeli',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLedEkranSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLoopDedektorSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLoopKabloCesidi',
            field=models.CharField(blank=True, choices=[('0.75mm² NYAF', '0.75mm² NYAF'), ('1mm² NYAF', '1mm² NYAF'), ('1.5mm² NYAF', '1.5mm² NYAF'), ('2.5mm² NYAF', '2.5mm² NYAF')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLoopKabloMetresi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayLoopTrafoSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayMantarBariyerAciklama',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPanoOlcusu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPanoSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPanoTipi',
            field=models.CharField(choices=[('iç ortam ', 'iç ortam '), ('dış ortam', 'dış ortam')], default='yok', max_length=50),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPatchCordSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPatchCordTipi',
            field=models.CharField(choices=[('SC-LC', 'SC-LC'), ('SC-SC', 'SC-SC'), ('LC-LC', 'LC-LC')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPatchPanelEkKasetSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPatchPanelSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayPatchPanelTipi',
            field=models.CharField(choices=[('2 li', '2 li'), ('4 lu', '4 lu'), ('8 li', '8 li'), ('12 li', '12 li')], default='yok', max_length=25),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlaySpiralMetre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlaySpiralÇapı',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlaySwitchPoeMi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlaySwitchPortSayisi',
            field=models.CharField(choices=[('5', '5'), ('8', '8'), ('5+2', '5+2'), ('8+2', '8+2'), ('16+2', '16+2'), ('8+4', '8+4'), ('16+4', '16+4')], default='yok', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='kesifolaymalzeme',
            name='kesifOlayyeradi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kesifolaymalzeme',
            name='kesifOlayDirekSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifolaymalzeme',
            name='kesifOlayKameraSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kesifolaymalzeme',
            name='kesifOlaySwitchSayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
