# Generated by Django 3.2.15 on 2022-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0107_auto_20221110_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='kesifolaymalzeme',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='kesifptsmalzeme',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
