# Generated by Django 3.2.15 on 2022-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0108_auto_20221117_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesif',
            name='kesifCreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
