# Generated by Django 3.2.15 on 2022-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0109_kesif_kesifcreatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesif',
            name='kesifCreateTime',
        ),
        migrations.AddField(
            model_name='kesif',
            name='kesifOnaylandiMi',
            field=models.BooleanField(default=False),
        ),
    ]
