# Generated by Django 3.2.15 on 2022-11-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0112_alter_paylasim_gönderiaciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='KesifCCTVMalzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kesifCCTVyeradi', models.CharField(blank=True, max_length=50, null=True)),
                ('kesifCCTVKameraSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVKameraBoatSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVKameraAdaptorSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVExtraKameraAdaptorSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVKameraTipi', models.CharField(blank=True, max_length=25, null=True)),
                ('kesifCCTVExtraKameraSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVExtraKameraTipi', models.CharField(blank=True, choices=[('yok', 'yok'), ('IPC-HFW1431TP-ZS 4MP', 'IPC-HFW1431TP-ZS 4MP'), ('IPC-HFW5231EP-Z 2MP', 'IPC-HFW5231EP-Z 2MP'), ('Muhafazalı Set (Box)', 'Muhafazalı Set (Box)')], max_length=25, null=True)),
                ('kesifCCTVDirekSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVDirekUzunlugu', models.CharField(blank=True, max_length=25, null=True)),
                ('kesifCCTVFlanshSayisi', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=25)),
                ('kesifCCTVDirekAçıklama', models.TextField(blank=True, max_length=200, null=True)),
                ('kesifCCTVAdaptorSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVPanoTipi', models.CharField(choices=[('iç ortam ', 'iç ortam '), ('dış ortam', 'dış ortam')], default='yok', max_length=50)),
                ('kesifCCTVPanoOlcusu', models.CharField(blank=True, max_length=50, null=True)),
                ('kesifCCTVPanoSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVCCTVkablometre', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVCCTVkabloTipi', models.CharField(choices=[('2+1', '2+1'), ('4+1', '4+1')], default='yok', max_length=50)),
                ('kesifCCTVEnerjikablometre', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVEnerjikabloTipi', models.CharField(choices=[('3x1.5 TTR', '3x1.5 TTR'), ('3x2.5 TTR', '3x2.5 TTR'), ('2x1.5 TTR', '2x1.5 TTR')], default='yok', max_length=50)),
                ('kesifCCTVDT8kablometre', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVSpiralMetre', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVBariyerSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVSpiralÇapı', models.CharField(blank=True, max_length=25, null=True)),
                ('kesifCCTVKayitCihaziSayisi', models.IntegerField(blank=True, null=True)),
                ('kesifCCTVKayitCihaziModeli', models.CharField(blank=True, choices=[('4 lu', '4 lu'), ('8 li', '8 li'), ('16 lı', '16 lı'), ('32 li', '32 li'), ('64 lü', '64 lü')], max_length=25, null=True)),
                ('kesifCCTVKayitCihaziHDDGigaByte', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='kesif',
            name='KesifCCTVMalzemelerid',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.kesifcctvmalzeme'),
        ),
    ]
