# Generated by Django 3.2.15 on 2022-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0113_auto_20221118_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesifcctvmalzeme',
            name='kesifCCTVKayitCihaziHDDGigaByte',
        ),
        migrations.AddField(
            model_name='kesifcctvmalzeme',
            name='kesifCCTVKayitCihaziHDDTeraByte',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
