# Generated by Django 3.2.16 on 2022-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0115_remove_kesifcctvmalzeme_kesifcctvbariyersayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesif',
            name='kesifYapilanYerAdi',
            field=models.CharField(help_text='Bu Alan Zorunludur', max_length=50),
        ),
    ]
